### DISCUSSION TITLE
Dynamic Table of Contents Page Numbers

### DISCUSSION THREAD

**Discussion by GlitchWitch** [spatie/browsershot#639] [Q&A]
Has anyone here ever successfully setup a dynamic table of contents?

We are trying to convert an existing template used in Google docs with a ToC on page 2, however since the titles for content can be on different pages depending on the height of the content the ToC page numbers are not static.

Any suggestions for how to handle this besides just removing the ToC page numbers all together?

**Comment by mutschler** [comment]
So I'd use something like:
```css
ul.toc li a::after {
  content: target-counter(attr(href), page);
  float: right;
}
```
See: https://www.w3.org/TR/css-gcpm-3/#target-counter
i don't think chrome supports `target-counter` out-of-the-box so you might need to polyfill that
