### DISCUSSION TITLE
Running Browsershot with Laravel Sail on M1 Apple silicon

### DISCUSSION THREAD

**Discussion by Johannes-Werbrouck** [spatie/browsershot#711] [Show and tell]
This is a guide for getting Browsershot to work on Apple silicon macs. As many have experienced, getting Browsershot fully functional in a Docker environment is not easy peasy lemon squeezy on macs with Apple silicon. The main issue is this: One of the requirements is the installation of puppeteer, which will install chromium automatically. But, on M1 (or M2) macs, there is no chromium package available for the arm64 architecture. Now, you could be tricked into setting the platform tot amd64 in your docker compose file, but that will open a can of worms you really want to keep closed. In short, it'll string you along by making you think it's technically possible, but the virtualization will ultimately prevent you from getting the chromium package to work. 

So, what is the solution then? 
It is possible to install Puppeteer and Browsershot in your laravel container, and point Puppeteer to a different container that has chromium installed. Cue the Alpine-chromium image from Zenika: https://github.com/Zenika/alpine-chrome . This is a small image that just runs chromium headless, exactly what we need!

We'll need to adjust some settings, so here's what I added in my docker-compose.yml: 
```
    chromium:
        image: zenika/alpine-chrome
        command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
        cap_add:
            -   SYS_ADMIN
        ports:
            - '9222:9222'
        networks:
            sail:
                ipv4_address: 172.22.0.100
```
Notice the networks section: The chromium container gets a static IP. To enable this, we need to change our sail network a bit, it will look like this: 
```
networks:
    sail:
        ipam:
            driver: default
            config:
                - subnet: "172.22.0.1/24"
```

And finally, here's how I use Browsershot: 

```
Browsershot::url("http://host.docker.internal/showPDF")
            ->setRemoteInstance('172.22.0.100', '9222')
            ->authenticate($request->user()->email, $request->user()->password)
            ->waitUntilNetworkIdle()
            ->format('A4')
            ->showBackground()
            ->savePdf("pdf/" . now()->format('y-m-d_H-i-s') . '.pdf');
```

The chromium container doesn't have these assets on its filesystem, so I'm using url() instead of html() so all the assets (css, js, images) are served correctly from the Laravel container. The showBackground() is to insure that all Tailwind classes are loaded properly.

I hope this helps, and don't hesitate to give feedback!

**Comment by ap1969** [comment]
Works for me (using the same approach on Windows with WSL)! Thanks for sharing Johannes.

**Comment by charlie87041** [comment]
oh my goshhh .  100 points for this

**Comment by carlos9108** [comment]
A little contribution to this great post. I needed to use `Browsershot::view `instead of `Browsershot::url`, yet I was in the same situation: independent containers for app and chromium. So what I did was to share the /tmp dir( as volumes in my docker-compose) between both containers, that way chromium would have access to the temp view I generated this way:

```
$view =  View::make($viewName, compact('asset', 'fields', 'thumbnails'));
 $browserShot = Browsershot::html($view)->setRemoteInstance($ip, $port);
```

Dont know if is possible change the dir where the temp view file stores though. That would be interesting, since we could create custom volume and not necessarily /temp dir. Yet this works for me. Again thnaks @Johannes-Werbrouck for this  post

**Comment by MuhammedAlkhudiry** [comment]
in my situation when I print google `Browsershot::url('https://google.com')` it works, but does not work with localhost `Browsershot::url('http://localhost')`, any idea why?

thank you for your help!

**Reply by Johannes-Werbrouck** [reply]
In my example, the **laravel** container is different from the **chromium** container. if you do `Browsershot::url('http://localhost')`, you're doing it in the **chromium** container, which does not have a web server. 
I guess (guess!) using the laravel container's hostname instead of `localhost` should work. If you have exposed port 80 on the Laravel container to port 80 on your host machine, then using `host.docker.internal` instead of `localhost` should work as well. That's how I do it.
I'd suggest reading up on docker networking. Good luck!

**Comment by roysgirit** [comment]
```
chromium:
        image: zenika/alpine-chrome:latest
        command: [ chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
        cap_add:
            - SYS_ADMIN
        ports:
            - '9222:9222'
        volumes:
            -  './public/pdf/tmp:/var/www/html/public/pdf/tmp'
        networks:
            sail:
                ipv4_address: 172.22.0.100
                
       Browsershot::html($html)
            ->setRemoteInstance('172.22.0.100', 9222)
            ->setCustomTempPath(public_path() . '/pdf/tmp')
            ->format('A4')
            ->windowSize(1280, 720)
            ->waitUntilNetworkIdle()
            ->showBackground()
            ->pdf();               
```

**Reply by Johannes-Werbrouck** [reply]
If I read this correctly, you are just sharing the `pdf/tmp` folder between the containers. Fine, but how would the css work in the chromium container?
Also, some comments or explanation might be helpful 😉

**Reply by charlie87041** [reply]
> ```
> chromium:
>         image: zenika/alpine-chrome:latest
>         command: [ chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
>         cap_add:
>             - SYS_ADMIN
>         ports:
>             - '9222:9222'
>         volumes:
>             -  './public/pdf/tmp:/var/www/html/public/pdf/tmp'
>         networks:
>             sail:
>                 ipv4_address: 172.22.0.100
>                 
>        Browsershot::html($html)
>             ->setRemoteInstance('172.22.0.100', 9222)
>             ->setCustomTempPath(public_path() . '/pdf/tmp')
>             ->format('A4')
>             ->windowSize(1280, 720)
>             ->waitUntilNetworkIdle()
>             ->showBackground()
>             ->pdf();               
> ```

You need to share te browsershot tmp files directory, which defaults to /tmp in linux. Otherwise, you are sending to the container one file path that does not exist. Check in my answer how I shared the /tmp dir across both container, althought you can also set a custom tmp dir for Browsershot and share that volume between containers(would be great if you post that here, for future references).
EDIT: didnt watch well, that is pretty much what I did. Check this:

- $html must ve a View instance. If plain html it could be a css issue as johannes says.
- blank page sometimes means lack of permissions in that directory.
- check that public_path() . '/pdf/tmp' actually stores the html view, if not, rendered view is stored somewhere else and you would need to volume-share that dir too.
- If it works in localhost, but not in deploy server, maybe you lack some dependencies in server, or lack of permissions in server, or even also the postman or whatever has some issue with the response(Happened to me with API Tester apk)

Anyway if you could be most explicit about what error throws or if blank page case, the better

**Reply by charlie87041** [reply]
If nothing helps you,  maybe this can tell you if any error is happening, as last  and despered resource only.

![image](https://user-images.githubusercontent.com/86492895/225625001-01179c7b-9e15-4876-8fd2-0a8ba1e862a2.png)


Just add a debug in Browsershot:894, because maybe the command is sending some error back alongside a sucessfull response

**Comment by thursdaydan** [comment]
Just come accross this thread and given it a try on my setup but get an error relating to the IP address.

`Error response from daemon: Invalid address 172.22.0.100: It does not belong to any of this network's subnets`

Here is my docker compose.

```
    chromium:
        image: zenika/alpine-chrome
        command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
        cap_add:
            -   SYS_ADMIN
        ports:
            - '9222:9222'
        volumes:
            -  './public/pdf/tmp:/var/www/html/public/pdf/tmp'
        networks:
            sail:
                ipv4_address: 172.22.0.100
networks:
    sail:
        ipam:
            driver: default
            config:
                - subnet: "172.22.0.1/24"
```

Does anyone have any ideas about what I might need to do differently?

**Comment by ArtemPD** [comment]
Hello everyone, I am very grateful @Johannes-Werbrouck for this post as it has helped me greatly. I also want to share my solution, which may be useful to someone.
1)First of all, we need update docker-compose.yml (we will add chromium service-container) :

```yaml
chromium:
  image: zenika/alpine-chrome
  command:
    [
      chromium-browser,
      "--headless",
      "--disable-gpu",
      "--remote-debugging-address=0.0.0.0",
      "--remote-debugging-port=9222",
    ]
  cap_add:
    - SYS_ADMIN
  volumes:
    - tmpfiles:/tmp
  ports:
    - "9222:9222"
  networks:
    sail:
      ipv4_address: 172.22.0.100
```

2)The chromium service-container use a static IP, so we need to update our sail network:

```yaml
networks:
  sail:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.1/24"
```

3)In the next step, you should update volumes:

```yaml
volumes:
    tmpfiles:
        driver: local
```

4)Don't forget add this volume to your service-container with laravel:

```yaml
services:
    laravel.test:  # Here will be name of your service-container
		...
		 volumes:
                  - 'tmpfiles:/tmp' # This line
                  - '.:/var/www/html'
		...
	        depends_on:
		 - chromium # This line too
```
Item 5: Rebuild docker

```bash
# Step 1: Stop the containers
./vendor/bin/sail down

# Step 2: Rebuild the containers without cache
./vendor/bin/sail build --no-cache

# Step 3: Start the containers
./vendor/bin/sail up
```

Thats all, now you can use browsershot like this 

```php
$bs = Browsershot::html($html)
            ->format('A4')
            ->showBackground()
            ->margins(10, 10, 10, 10);
if (config('browser-shot.HOST')) {
    $bs->setRemoteInstance(config('browser-shot.HOST'), '9222')
        ->waitUntilNetworkIdle();
}

return $bs->pdf();
```

for convenience, i have created browser-shot.php in config directory

```php
<?php

return [
    'PATH_CHROME' => env('PATH_CHROME'),
    'PATH_NODE_MODULES' => env('PATH_NODE_MODULES'),
    'HOST' => env('BROWSERSHOT_CHROMIUM_HOST', '127.0.0.1'),
    'NODE' => env('NODE', '/usr/bin/node'),
    'NPM' => env('NPM', '/usr/bin/npm'),
];
```

Don't forget add this line to your env file 

BROWSERSHOT_CHROMIUM_HOST=172.22.0.100

Have a good day!

**Reply by nprasath002** [reply]
This worked like a charm. Thanks @ArtemPD and @Johannes-Werbrouck

**Reply by Calaelen** [reply]
Thanks for the great install docs. Everything makes sense but my system still reports "Error: Cannot find module 'puppeteer'"  :(

Full Error (the new IP as remote seems to be used)

> NODE_PATH=`npm root -g` node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/1219118405-0597526001709823183\/index.html","action":"pdf","options":{"args":["--no-sandbox"],"viewport":{"width":800,"height":600},"displayHeaderFooter":false,"remoteInstanceUrl":"http:\/\/172.22.0.100:9222","waitUntil":"networkidle0","printBackground":true}}'" failed. Exit Code: 1(General error) Working directory: /var/www/html/public Output: ================ Error Output: ================ node:internal/modules/cjs/loader:1144 const err = new Error(message); ^ Error: Cannot find module 'puppeteer' Require stack: - /var/www/html/vendor/spatie/browsershot/bin/browser.cjs at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15) at Module._load (node:internal/modules/cjs/loader:985:27) at Module.require (node:internal/modules/cjs/loader:1235:19) at require (node:internal/modules/helpers:176:18) at callChrome (/var/www/html/vendor/spatie/browsershot/bin/browser.cjs:67:28) at Object.<anonymous> (/var/www/html/vendor/spatie/browsershot/bin/browser.cjs:424:5) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) { code: 'MODULE_NOT_FOUND', requireStack: [ '/var/www/html/vendor/spatie/browsershot/bin/browser.cjs' ] } Node.js v20.11.0

**Reply by rpringadi** [reply]
I encountered the same error. Any fix for this?

**Reply by daisyvaassen** [reply]
It may be pretty late, but thanks for this information. This worked perfect on my Mac M1!

**Comment by horuskol** [comment]
Great solution, and some good writeups.

Is there a reason that the chromium container must use a static IP? I'd like to get this working over a bridge network and use the built-in name resolution instead - but it seems when I do this, something fails and browsershot is falling back to trying to run chrome in the app container.

```
version: '3'
services:
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                NODE_VERSION: '${NODE_VERSION:-18}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - 'sail-tmp:/tmp'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - minio
            - chromium
    chromium:
        image: zenika/alpine-chrome
        command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'sail-tmp:/tmp'
        ports:
            - '9222:9222'
        networks:
            - sail
        extra_hosts:
            - 'host-docker-internal:host-gateway'
networks:
    sail:
        driver: bridge
volumes:
    sail-tmp:
        driver:  local
```

**Reply by Johannes-Werbrouck** [reply]
I think Browsershot (Puppeteer, really) can only take an IP address as the remote instance, not a hostname. Here's why I suspect this is the case: 
- Puppeteer's RemoteAddress interface has `ip` and `port` : https://pptr.dev/api/puppeteer.remoteaddress/
- Browsershot's documentation also only talks about IP address: https://spatie.be/docs/browsershot/v2/miscellaneous-options/connection-to-a-remote-chrome-instance

**Reply by horuskol** [reply]
Yeah, there was some deeper issue in the puppeteer/chrome interface that forced the IP address.

We were able to resolve the problem by setting up two networks - a bridge and an ipam/default one. Most of the containers (mysql, redis, etc) are on the bridged network letting us use service name resolution, the chrome container was on the second network, and the main app container was on both. Seems to be working well enough.

**Reply by vpratfr** [reply]
For anyone who struggles with setting up fixed IP addresses, here is a small workaround we use:

```
// Config file
'chromium_host' => env('CHROMIUM_HOST', 'chromium'),

// Code to produce the PDF
$host = config('browsershot.chromium_host');
if (!filter_var($host, FILTER_VALIDATE_IP) {
    $host = gethostbyname($host);
}

// $host now contains the IP
```

Add on top of that some caching and that should be fine.

On production environment setting the env to 127.0.0.1 bypasses all that.

**Reply by nezaboravi** [reply]
@horuskol would be great if you can provide example of how you resolved problem by set
ting up two networks?

**Comment by cAstraea** [comment]
Would this work similar on amazon graviton instance t4g ?

**Comment by hyphen81** [comment]
Trying to get this up and running, also trying to pass a view to browsershot, not using the url method. I'm getting the error:

`Exit Code: 1(General error) Working directory: /var/www/html/public Output: ================ Error Output: ================ Error: net::ERR_FILE_NOT_FOUND at file:///tmp/237010668-0266164001697980976/index.html`

Presumably I've misconfigured the volumes or something.

I noticed one person on this thread had a solution involving adding a volume for 'tmpfiles:/tmp', and another person added ` './public/pdf/tmp:/var/www/html/public/pdf/tmp'` to the volumes on the chromium service. I've tried just doing the `/tmp` directory, and then I tried adding the additional volumes to the chromium service and I still get the above error regardless.

I'm not sure how to get this working. Any ideas?

I guess I'm not understanding why it's looking for a file. My `$view` variable below contains html. 
```
 $view = View::make('pdf.customer-deposits', ['data' => $data])->render();

            $bs = Browsershot::html($view)
                ->format('A4')
                ->margins(10, 10, 10, 10)
                ->setRemoteInstance('127.0.0.1', '9222')
                ->pdf();      
```

UPDATE:

I added this line 
`->setCustomTempPath('/var/www/html/public/pdf/tmp')`

and now I get `mkdir(): Permission denied`, which I guess is progress. 

UPDATE 2:

In case this helps anyone else, I ran: `docker exec -u root -it my-image-name /bin/sh`
then `chown -R chrome:chrome /var/www/html/public/pdf/tmp`

Which allowed it to work. It generated the PDF, however, it has no styling :( but that seems like another issue.

**Reply by Johannes-Werbrouck** [reply]
Make sure the view (`pdf.customer-deposits` in your case) includes your app.css or the layout that includes it. In my projects I'll include a print-layout that includes the fonts and the vite scripts. This will be used as layout for every component that needs to be printed.

**Reply by hyphen81** [reply]
I do have a separate layout that I'm extending for the pdf views. I was able to get this working, but I forget now what the missing piece of the puzzle was..

**Reply by rw152** [reply]
I'm struggling with this right now as well (getting the styling / javascript output from vue to generate). I will post an update if I get it working.

**Reply by rw152** [reply]
OK, friends. Figured how to get it working for me in my configuration **vue3 + vite**

It boiled down to realizing there was probably some kind of issue with the communication between the chromium container and my Laravel container. To see what was going on, I did the obligatory die/dump to review the consoleMessages from the URL being accessed by Browsershot 

```php
dd($pdf->consoleMessages());
```

I saw a bunch of ERR_CONNECTION_REFUSED errors like:

```
0 => array:4 [▶
    "type" => "error"
    "message" => "Failed to load resource: net::ERR_CONNECTION_REFUSED"
    "location" => array:1 [▼
      "url" => "http://localhost:5173/@vite/client"
    ]
    "stackTrace" => array:1 [▼
      0 => array:1 [▼
        "url" => "http://localhost:5173/@vite/client"
      ]
    ]
  ]
```

Note localhost... I noticed after shelling into my chromium container that I could not wget into localhost or 127.0.0.1, but I could access laravel.test (this is likely due to Docker's isolation practices, etc...)

I then modified by ```.env``` file and ```vite.config.js``` file.

**.env**
```.env
APP_URL=http://laravel.test
APP_SERVICE=laravel.test
```
_laravel.test_ would be whatever the main service in your docker-composer file is called

I then modified the server block of my vite.config.js file:

```js
...
server: {
        cors: true,
        hmr: {
            host: 'laravel.test',
        },
        host: 'laravel.test'
    },
...
```

I realize this configuration may not be helpful for those of you running sail/docker in production, but this is what I needed to do locally for development.

**Note:** I'm using an arm64 silicon (like I assume most of you here are). To ensure I could access laravel.test from my browser I modified the /etc/hosts file on my Mac to look like the following:

**/etc/hosts**
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
127.0.0.1       laravel.test
255.255.255.255 broadcasthost
::1             localhost
::1             laravel.test
```

**Comment by imsyuan** [comment]
> This is a guide for getting Browsershot to work on Apple silicon macs. As many have experienced, getting Browsershot fully functional in a Docker environment is not easy peasy lemon squeezy on macs with Apple silicon. The main issue is this: One of the requirements is the installation of puppeteer, which will install chromium automatically. But, on M1 (or M2) macs, there is no chromium package available for the arm64 architecture. Now, you could be tricked into setting the platform tot amd64 in your docker compose file, but that will open a can of worms you really want to keep closed. In short, it'll string you along by making you think it's technically possible, but the virtualization will ultimately prevent you from getting the chromium package to work.
> 
> So, what is the solution then? It is possible to install Puppeteer and Browsershot in your laravel container, and point Puppeteer to a different container that has chromium installed. Cue the Alpine-chromium image from Zenika: https://github.com/Zenika/alpine-chrome . This is a small image that just runs chromium headless, exactly what we need!
> 
> We'll need to adjust some settings, so here's what I added in my docker-compose.yml:
> 
> ```
>     chromium:
>         image: zenika/alpine-chrome
>         command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
>         cap_add:
>             -   SYS_ADMIN
>         ports:
>             - '9222:9222'
>         networks:
>             sail:
>                 ipv4_address: 172.22.0.100
> ```
> 
> Notice the networks section: The chromium container gets a static IP. To enable this, we need to change our sail network a bit, it will look like this:
> 
> ```
> networks:
>     sail:
>         ipam:
>             driver: default
>             config:
>                 - subnet: "172.22.0.1/24"
> ```
> 
> And finally, here's how I use Browsershot:
> 
> ```
> Browsershot::url("http://host.docker.internal/showPDF")
>             ->setRemoteInstance('172.22.0.100', '9222')
>             ->authenticate($request->user()->email, $request->user()->password)
>             ->waitUntilNetworkIdle()
>             ->format('A4')
>             ->showBackground()>             ->savePdf("pdf/" . now()->format('y-m-d_H-i-s') . '.pdf');
> ```
> 
> The chromium container doesn't have these assets on its filesystem, so I'm using url() instead of html() so all the assets (css, js, images) are served correctly from the Laravel container. The showBackground() is to insure that all Tailwind classes are loaded properly.
> 
> I hope this helps, and don't hesitate to give feedback!

It's work for me. Thank you @Johannes-Werbrouck

**Comment by robertbakker1** [comment]
Simple setup using default Sail without subnets and static IP, works for me on Apple M2 with OrbStack:

Add to docker-compose.yml
```
    chromium:
        image: zenika/alpine-chrome
        command: [ "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
        cap_add:
            - SYS_ADMIN
        networks:
           - sail
```

Found the browser instance wanted an IP so I gave it just that with `gethostbyname()`:
```php
Browsershot::url('https://example.com')
    ->setRemoteInstance(gethostbyname('chromium'))
    ->savePdf(__DIR__ . '/example.pdf');
 ```
