### ISSUE TITLE
PDF page orientation per page possible?

### ISSUE THREAD

**Issue by rask** [spatie/browsershot#158]
I'm looking for a solution to print out a web page as a PDF, with the first page being in portrait orientation while the rest are in landscape orientation. This is experimentally supported (from what I understand) via something like

```css
@page {
    size: A4 landscape;
}

@page :first {
    size: A4 portrait;
}
```

Would browsershot and the visualization dependencies be able to handle this properly?
